// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVQC2Bf9dg84C2BWn1zz5RHRAHbzx9h6Q',
    appId: '1:295606848490:web:52082e55d589d2751dc093',
    messagingSenderId: '295606848490',
    projectId: 'fir-web-auth-ec945',
    authDomain: 'fir-web-auth-ec945.firebaseapp.com',
    storageBucket: 'fir-web-auth-ec945.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvvJxn6PaSPRpeQznW13l5LHVwKPq3dnY',
    appId: '1:295606848490:android:0c77cd7a2081449c1dc093',
    messagingSenderId: '295606848490',
    projectId: 'fir-web-auth-ec945',
    storageBucket: 'fir-web-auth-ec945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdvXhKtLcbSJa0XRiGKD0_YUR8xKjeoUk',
    appId: '1:295606848490:ios:da271df755c0078b1dc093',
    messagingSenderId: '295606848490',
    projectId: 'fir-web-auth-ec945',
    storageBucket: 'fir-web-auth-ec945.appspot.com',
    iosClientId: '295606848490-6ta45jf3i4b9hddflgjuhmn618cq4k1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase270623',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdvXhKtLcbSJa0XRiGKD0_YUR8xKjeoUk',
    appId: '1:295606848490:ios:afc596fce79bdca11dc093',
    messagingSenderId: '295606848490',
    projectId: 'fir-web-auth-ec945',
    storageBucket: 'fir-web-auth-ec945.appspot.com',
    iosClientId: '295606848490-75ia7ts24uo0qn6bf8oji2r4ckfhuqc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase270623.RunnerTests',
  );
}
